# Relative path(s) to your source files
source: build

# Relative path where you want the documentation to be built
destination: docs

# The path that contains supporting assets for the documentation page
documentation_assets: ./node_modules/hologram-github-theme

# Category that will be used as the index.html (optional)
index: docs

# The global title that is displayed at the top of the pages
global_title: Stencil

# The CSS files to be included in the styleguide
css_include:
  - '../build/stencil.css'

# To output navigation for top level sections, set the value to
# 'section'. To output navigation for sub-sections, set the value to `all`
nav_level: section
